### ISSUE TITLE
Feature request: change size/hide left panel

### ISSUE THREAD

**Issue by alexander-ii** [tyrasd/latest-changes#5]
Imho, to give a 50% of space to the list of changesets is a little overkill. I would prefer to see more space for a map and changes on the map.

**Comment by ximex** [comment]
maybe make something like:
```css
#left {
  width: 50%;
  max-width: 400px;
}
#right {
  width: calc(100% - 400px);
  min-width: 50%;
}
```
